---
book_repo: pivotal-cf/docs-book-app-automator
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-app-automator
    ref: '1.0'
  directory: app-automator/1-0
  subnav_template: app_automator_1_0_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    changelog_href: https://docs.pivotal.io/app-automator/1-0/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: App Automator for PCF
    search_placeholder: Search App Automator for PCF
    url_prefix: app-automator/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list: